version: '3.8'

services:
  # Runs QSSTV and publishes images to a shared vol
  Houston-SSTV:
    build: Houston-SSTV
    image: houston/sstv:v1
    environment:
      - PULSE_SERVER=tcp:10.85.3.155:34567
    volumes:
      - type: volume
        source: sstv-data
        target: /mnt/sstv-data
        # UID is important!
      - type: bind
        source: /run/user/1000/pulse
        target: /tmp/pulsesocket

volumes:
  # Shared volume for saved sstv pictures
  sstv-data:
