version: "3.8"

services:
  core:
    restart: "no"
    build: MC-Core
    image: kw1fox1/mc-core:v1

  db:
    image: postgres
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=admin_bot_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    tmpfs: /var/lib/postgresql/data
