version: '3.8'

services:
  # # Runs QSSTV and publishes images to a shared vol
  # Houston-SSTV:
  #   build: Houston-SSTV
  #   image: houston/sstv:v1
  #   environment:
  #     - PULSE_SERVER=tcp:10.85.3.155:34567
  #   privileged: true
  #   networks:
  #     - default
  #   ports:
  #     - 8888:8888
  #   volumes:
  #     - type: volume
  #       source: sstv-data
  #       target: /mnt/sstv-data
  #       # UID is important!
  #     - type: bind
  #       source: /run/user/1000/pulse
  #       target: /tmp/pulsesocket

  # Robotstreamer endpoint
  Houston-Streamer:
    environment:
      STREAMKEY: "Idk"
    build: Houston-Streamer
    image: houston/streamer:v1
    networks:
      - default

  # Direwolf sound card TNC
  Houston-Direwolf:
    build: Houston-Direwolf
    image: houston/direwolf:v1
    volumes:
      # UID is important!
      - type: bind
        source: /run/user/1000/pulse
        target: /tmp/pulsesocket

  Houston-UI:
    build: Houston-UI
    image: houston/ui:v1
    depends_on:
      - Houston-db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://user:pass@Houston-db/test
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  Houston-db:
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  # Shared volume for saved sstv pictures
  sstv-data:
