# Joe wrote this

install:
	sudo cp qsstv.service /etc/systemd/system/qsstv.service
	sudo cp robotstreamer.service /etc/systemd/system/robotstreamer.service
	sudo systemctl daemon-reload
	sudo systemctl enable qsstv.service
	sudo systemctl enable robotstreamer.service
