version: "3.7"

services:
  db:
    image: postgres:10.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=houston
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    tmpfs: /var/lib/postgresql/data

  Houston-UI:
    image: houston_ui:$TAG
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - "db:db"
    ports:
      - "8080:8080"
    restart: "no"
