# Joe wrote this

install:
	sudo cp qsstv.service /etc/systemd/system/qsstv.service
	sudo systemctl daemon-reload
	sudo systemctl enable qsstv.service
	sudo cp qsstv_9.0.conf /home/houston/.config/ON4QZ/qsstv_9.0.conf
