name: Formatting and Checks
on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:

jobs:
  formatblack:
    name: Style Check Code with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check files using the black formatter
        uses: rickstaa/action-black@v1
        id: action_black
        with:
          black_args: "."

      - name: Annotate diff changes using reviewdog
        if: steps.action_black.outputs.is_formatted == 'true'
        uses: reviewdog/action-suggester@v1
        with:
          tool_name: blackfmt

      - name: Fail if actions taken
        if: steps.action_black.outputs.is_formatted == 'true'
        run: exit 1

  testRobotBridge:
    name: Test Robot Bridge
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this build
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install deps
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          cd robot_bridge && pipenv install --deploy --dev

      - name: Run tests
        run: |
          cd robot_bridge && make test
